name: fastpine

on:
  push:
    branches:
      - main
    paths:
      - 'cockroach-alpine/**'
      - '.github/workflows/cockroach-alpine.yml'
  workflow_run:
    workflows: ["glibcpine"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./cockroach-alpine
          file: ./cockroach-alpine/Dockerfile
          push: true
          build-args: | 
            "COCKROACH_VERSION=${{ env.COCKROACH_VERSION }}"
            "ALPINE_VERSION=${{ env.ALPINE_VERSION }}"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cockroachpine:${{ env.COCKROACH_VERSION }}-alpine${{ env.ALPINE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cockroachpine:latest
