name: glibcpine

on:
  push:
    branches:
      - main
    paths:
      - 'glibc-alpine/**'
      - '.github/workflows/glibc-alpine.yml'
env:
  ALPINE_VERSION: "3.20"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./glibc-alpine
          file: ./glibc-alpine/Dockerfile
          push: true
          build-args: | 
            "ALPINE_VERSION=${{ env.ALPINE_VERSION }}"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/glibcpine:${{ env.ALPINE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/glibcpine:latest 
