name: javapine

on:
  push:
    branches:
      - main
    paths:
      - 'java-alpine/**'
      - '.github/workflows/java-alpine.yml'
env:
  ALPINE_VERSION: "3.20"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    strategy:
      matrix:
        java_version: [11, 17, 21]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./java-alpine/Dockerfile
          push: true
          build-args: |
              JAVA_VERSION: ${{ matrix.java_version }}
              ALPINE_VERSION: ${{ env.ALPINE_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/javapine-${{ JAVA_VERSION }}:${{ env.ALPINE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/javapine-${{ JAVA_VERSION }}:latest