name: postgrepine

on:
  push:
    branches:
      - main
    paths:
      - 'postgres-alpine/**'
      - '.github/workflows/postgres-alpine.yml'
env:
  ALPINE_VERSION: "3.20"
  POSTGRES_VERSION: "16"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./postgres-alpine
          file: ./postgres-alpine/Dockerfile
          push: true
          build-args: | 
            "ALPINE_VERSION=${{ env.ALPINE_VERSION }}"
            "POSTGRES_VERSION=${{ env.POSTGRES_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/postgrepine:${{ env.POSTGRES_VERSION }}alpine-${{ env.ALPINE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/postgrepine:latest 
