name: Build and Push Python-Alpine Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'python-alpine'
      - '.github/workflows/python-alpine.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./python-alpine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-apline:latest
